name: lib_uikit_example
description: Example app for lib_uikit

dependencies:
  flutter:
    sdk: flutter
  lib_uikit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

environment:
  sdk: ^3.7.0-323.0.dev