name: force_wallet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


  ## local dependences
  lib_base:
    path: ./packages/lib_base
  lib_uikit:
    path: ./packages/lib_uikit
  lib_chain_manager:
    path: ./packages/lib_chain_manager
  lib_network:
    path: ./packages/lib_network
  lib_storage:
    path: ./packages/lib_storage
  lib_token_manager:
    path: ./packages/lib_token_manager
  lib_wallet_manager:
    path: ./packages/lib_wallet_manager
    # wallet core
  flutter_trust_wallet_core:
    path: ./packages/flutter_trust_wallet_core
  lib_web3_core:
    path: ./packages/lib_web3_core
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true