name: lib_web3_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0-323.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: 2.7.3
  big_decimal: 0.5.0
  dart_bech32: 2.0.0
  convert: 3.1.1
  flutter_emoji: 2.5.1
  # 比特币WIF编码
  dart_wif: 2.1.1
  on_chain: 6.1.0
    # EVM签名工具
  eth_sig_util: 0.0.9
  lib_base:
    path: ../lib_base
  flutter_trust_wallet_core:
    path: ../flutter_trust_wallet_core
  decimal: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lib_chain_manager:
    path: ../lib_chain_manager

flutter:
