name: flutter_trust_wallet_core
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0-323.0.dev
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  protobuf: ^2.1.0
  fixnum: ^1.1.0
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: org.ab.newpay.flutter_trust_wallet_core.flutter_trust_wallet_core
        pluginClass: FlutterTrustWalletCorePlugin
      ios:
        pluginClass: FlutterTrustWalletCorePlugin
      web:
        pluginClass: FlutterTrustWalletCoreWeb
        fileName: flutter_trust_wallet_core_web.dart


ffigen:
  name: TrustWalletCore
  description: Bindings to `gen/headers/**.h
  output:
    bindings: 'gen/ffigen_output/generated_bindings.dart'
  headers:
    entry-points:
      - 'gen/headers/**.h'
  compiler-opts: '-I/opt/homebrew/opt/llvm/  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ -Wno-nullability-completeness'
